fix: remove surefire-junit47 dependency resulting in non-zero exit code
browserstack/serenity-browserstack pull request #48
Opened 2024-01-08 11:38 UTC by kamal-kaur04

2024-01-08 14:17 UTC, karanshah-browserstack requested changes

2024-01-08 14:17 UTC, karanshah-browserstack commented on pom.xml
> -                <dependencies>
Why are we removing this?

2024-01-08 15:44 UTC, kamal-kaur04 commented on pom.xml
> -                <dependencies>
Closed on call.

2024-01-09 05:57 UTC, karanshah-browserstack approved these changes

2024-01-09 10:56 UTC, merged